### ISSUE TITLE
PyYaml Upgrade

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#177]
``Hello,

I had a issue with the change:
https://github.com/tguisep/optscale/commit/99d8698cbee3a5ab5e0b870e5df2c8124177d582#diff-94de2f2a2862f02e0ef3cce9eaf6b29075c05fc3fd0a60ab23726aa7f7971ad4R2

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/thomas/Documents/PRJ/optscale/optscale-deploy/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/thomas/Documents/PRJ/optscale/optscale-deploy/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/thomas/Documents/PRJ/optscale/optscale-deploy/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    
```

Fix: rollback on PyYAML==5.3.1

**Comment by maxb-hystax** [comment]
Thanks Thomas, checking from our side.

**Comment by maxb-hystax** [comment]
@tguisep please use Python 3.9 - it is the base for OptScale right now.
FYI - we are going to upgrade Python version to 3.12, just waiting while several third-party packages support it (for example - aliyun-python-sdk-core)
