### ISSUE TITLE
Getting below error when we ./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version> command

### ISSUE THREAD

**Issue by yogi-2023** [hystax/optscale#344]
(venv) root@ip-172-31-34-185:/optscale/optscale-deploy# ./runkube.py --with-elk -c ~/.kube/config -o overlay/user_template.yml -- myapp 2024070801-public
16:14:41.038: Pulling images for 172.31.34.185
16:14:41.045: Pulling image index.docker.io/hystax/arcee with tag 2024070801-public
Traceback (most recent call last):
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://172.31.34.185:2376/v1.35/images/create?tag=2024070801-public&fromImage=index.docker.io%2Fhystax%2Farcee

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/optscale/optscale-deploy/./runkube.py", line 457, in <module>
    acr.start(args.check, args.update_only)
  File "/optscale/optscale-deploy/./runkube.py", line 330, in start
    images = self.pull_images(docker_cl)
  File "/optscale/optscale-deploy/./runkube.py", line 147, in pull_images
    image = self._pull_image(docker_cl, image_name, self.version,
  File "/optscale/optscale-deploy/./runkube.py", line 133, in _pull_image
    image = docker_cl.images.pull(**params)
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 309, in pull
    self.client.api.pull(repository, tag=tag, **kwargs)
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/image.py", line 374, in pull
    self._raise_for_status(response)
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")

**Comment by stanfra** [comment]
Hi @yogi-2023, problem appears because you reached your images pull rate limit.Please read documentation from traceback: https://www.docker.com/increase-rate-limit to solve problem with limit

**Comment by yogi-2023** [comment]
Thank you for providing update. we have create new server also but getting same error.

**Comment by stanfra** [comment]
@yogi-2023, please create account in docker hub and log in to it on server before image pull
